### ISSUE TITLE
Home To Win

### ISSUE THREAD

**Issue by picard102** [plexinc-plugins/HGTV_Canada.bundle#20]
Episodes of Home To Win are not showing up.  Only one episode currently appears, may have something to do with the lack of the show being listed in all videos?

**Comment by sander1** [comment]
I can't find "Home To Win" at all inside the channel. Where exactly is it listed?

**Comment by picard102** [comment]
It's titled Leave it to Bryan and Scott.

**Comment by sander1** [comment]
> It's titled Leave it to Bryan and Scott.

I still can't find it :( How do I navigate to the item, what path do I have to click through?

**Comment by picard102** [comment]
6th from the bottom right now under most recent.

**Comment by sander1** [comment]
The channel and service have been updated. Should fix outstanding issues. If not, please create a new issue.
