### ISSUE TITLE
Recent episodes don't play

### ISSUE THREAD

**Issue by gagp** [plexinc-plugins/HGTV_Canada.bundle#23]
There seems to be an issue with the latest videos not playing. Anything older than two weeks seems to work fine but anything newer fails to load.

Thanks for looking into it.

**Comment by sander1** [comment]
Possibly related: https://github.com/plexinc-plugins/HGTV_Canada.bundle/issues/22

**Comment by codcheeks** [comment]
wondering if the plugin was updated, seems to be a problem with links up loading video, url has changed for episodes ,  thanks for the great work!

**Comment by gagp** [comment]
I have not seen any updates. @sander1 maybe with a crash course I can help maintain this one?

**Comment by sander1** [comment]
Should be fixed with latest set of changes to the URL Service (https://github.com/plexinc-plugins/Services.bundle/commit/9ee1afa157fac221f553caf2f616d37dbe0f2d4f).

**Comment by gagp** [comment]
Wroks like a charm!
